trainer: stage_inr
dataset:
  type: vimeo_arb
  path: ./data/vimeo90k/vimeo_septuplet
  aug: true

arch: 
  type: gimmvfi_f
  ema: true
  modulated_layer_idxs: [1]

  coord_range: [-1., 1.]

  hyponet:
    type: mlp
    n_layer: 5 # including the output layer
    hidden_dim: [128] # list, assert len(hidden_dim) in [1, n_layers-1]
    use_bias: true
    input_dim: 3
    output_dim: 2
    output_bias: 0.5
    activation:
      type: siren
      siren_w0: 1.0
    initialization:
      weight_init_type: siren
      bias_init_type: siren

loss:
  subsample:
    type: random
    ratio: 0.1

optimizer:
  type: adamw
  init_lr: 0.00008
  weight_decay: 0.00004
  betas: [0.9, 0.999] 
  ft: true
  warmup:
    epoch: 1
    multiplier: 1
    buffer_epoch: 0
    min_lr: 0.000008
    mode: fix
    start_from_zero: True
  max_gn: null

experiment:
  amp: True
  batch_size: 4
  total_batch_size: 32
  epochs: 60
  save_ckpt_freq: 10
  test_freq: 10
  test_imlog_freq: 10

